blank_issues_enabled: false
contact_links:
  - name: Discord Guild
    url: https://discord.gg/eUMSXGZ
    about: Ask any questions and voice your design concerns about the library in our Discord guild.
