using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Disqord")]
[assembly: InternalsVisibleTo("Disqord.Bot")]
[assembly: InternalsVisibleTo("Disqord.Extensions.Interactivity")]
[assembly: InternalsVisibleTo("Disqord.Extensions.Slash")]
[assembly: InternalsVisibleTo("Disqord.Extensions.Voice")]
[assembly: InternalsVisibleTo("Disqord.Rest")]
[assembly: InternalsVisibleTo("Disqord.Rest.Api")]
[assembly: InternalsVisibleTo("Disqord.Gateway")]
[assembly: InternalsVisibleTo("Disqord.Gateway.Api")]
[assembly: InternalsVisibleTo("Disqord.TestBot")]
[assembly: InternalsVisibleTo("Disqord.Voice")]
[assembly: InternalsVisibleTo("Disqord.Voice.Api")]
[assembly: InternalsVisibleTo("Disqord.Webhook")]
[assembly: InternalsVisibleTo("Disqord.OAuth2")]
